apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync
  namespace: newname
spec:
  vault: 
    name: junek8s23-kv # name of key vault
    object:
      name: pvtsshkeyazure # name of the akv object
      type: secret # akv object type
  output: 
    secret: 
      name: round1 # kubernetes secret name that we want to see in k8s
      dataKey: anything # key to store object value in kubernetes secret

---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   namespace: akv2k8s
#   annotations:
#     reloader.stakater.com/auto: "true"
#   labels:
#     app: nginx
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: mypod
#         image: redis
#         volumeMounts:
#         - name: foo
#           mountPath: "/etc/foo"
#           readOnly: true
#       volumes:
#       - name: foo
#         secret:
#           secretName: round1 #secret that we sync with akv2k8s in line 14
#           optional: true