apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync
  namespace: akv2k8s
spec:
  vault: 
    name: junek8s23-kv # name of key vault
    object:
      name: interview # name of the akv object
      type: secret # akv object type
  output: 
    secret: 
      name: round1 # kubernetes secret name that we want to see in k8s
      dataKey: anything # key to store object value in kubernetes secret